### PR TITLE
Move to bandolier.es2017 package

### PR DESCRIPTION
**Pull request by Protryon**

### CODE REVIEW

**Comment by Protryon** [comment]
@bakkot Up for review.

**Review by bakkot — APPROVED** [review]

**Review by bakkot — CHANGES_REQUESTED** [review]
j/k, [pom needs to be updated too](https://github.com/shapesecurity/bandolier/blob/b2f0574b8191a52a5251f5b99a63aa108b068c27/pom.xml#L6-L9).

**Comment by bakkot** [comment]
Might as well update the version while you're at it, I guess.

Because this is also published on [npm](https://www.npmjs.com/package/bandolier), where it will not be namespaced, I'd prefer to go to major version 2 (or 3) instead of resetting back to 1.

**Comment by Protryon** [comment]
@bakkot Version updated.

**Review by bakkot — APPROVED** [review]

**Comment by bakkot** [comment]
LGTM, but I'm going to shuffle some branches around before landing this.

**Pull request merged**
